# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052fabc93d70396db0b5b7296931b1e5877c4c30ab80bf94500c0b2195a5a885feae2e55a3a5a5442323c5f0c157e24d7e860f48dc578dab59000cb22698c513

test:
  secret_key_base: c04cdd48108cf72c6056158f82a390dba53761b5b300a04d553ec6563f615b863ee530f382f890d28ddfa31ee97bb88254dc99a952c9d736f68026cc348f7caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
